ktor:
  application:
    modules:
        - edu.kitt.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
  development: true
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password