ktor:
  application:
    modules:
        - edu.kitt.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
  development: true
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password